### ISSUE TITLE
Please rewrite the git history to properly remove your old credentials

### ISSUE THREAD

**Issue by FFY00** [00benallen/rust-deploy#1]
You probably changed your credentials already but you really should overwrite the git history to completely remove them.

You can do it as follows:

Let's start a rebase
```
git rebase -i --root
```

A file with the git history will be opened, you want to squash the first and last commits together. To do this you need to replace the `pick` before them with `s` (or `squash`). After that save and close the file editor.

Now you need to force push the new history.
```
git push --force
```

**Comment by 00benallen** [comment]
@FFY00 Thanks I've done this (I did change the credentials)
